services:
  postgres:
    image: postgres:16
    container_name: river_monitoring_db
    environment:
      POSTGRES_DB: river_monitoring
      POSTGRES_USER: river_user
      POSTGRES_PASSWORD: river_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
